name: 'Send Feishu Notification'
description: 'Send notifications to Feishu (飞书) via webhook'
branding:
  icon: 'send'
  color: 'blue'

inputs:
  message:
    description: 'Notification message content'
    required: true
  msg_type:
    description: 'Message type (text, post, or interactive)'
    required: false
    default: 'text'
  title:
    description: 'Message title for post/interactive messages'
    required: false

outputs:
  status:
    description: 'Notification delivery status'
    value: ${{ steps.run.outputs.status }}
  timestamp:
    description: 'ISO 8601 timestamp'
    value: ${{ steps.run.outputs.timestamp }}
  response:
    description: 'Webhook response or error message'
    value: ${{ steps.run.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: cd ${{ github.action_path }} && npm ci --production

    - name: Run notification
      id: run
      shell: bash
      env:
        FEISHU_WEBHOOK_URL: ${{ env.FEISHU_WEBHOOK_URL }}
        FEISHU_MESSAGE: ${{ inputs.message }}
        FEISHU_MSG_TYPE: ${{ inputs.msg_type }}
        FEISHU_TITLE: ${{ inputs.title }}
        HAGI_ACTION_MODE: "true"
      run: |
        cd ${{ github.action_path }}
        set +e
        OUTPUT=$(npx tsx src/feishu.ts)
        EXIT_CODE=$?

        if [ $EXIT_CODE -ne 0 ] || [ -z "$OUTPUT" ]; then
          STATUS="failure"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          RESPONSE="CLI execution failed with exit code $EXIT_CODE or no output"
        else
          if command -v jq &> /dev/null; then
            STATUS=$(echo "$OUTPUT" | jq -r '.status // "failure"')
            TIMESTAMP=$(echo "$OUTPUT" | jq -r '.timestamp // empty')
            RESPONSE=$(echo "$OUTPUT" | jq -r '.response // "No response"')
          else
            STATUS=$(node -e "try { const d = JSON.parse(require('fs').readFileSync(0, 'utf8')); console.log(d.status || 'failure'); } catch(e) { console.log('failure'); }" <<< "$OUTPUT")
            TIMESTAMP=$(node -e "try { const d = JSON.parse(require('fs').readFileSync(0, 'utf8')); console.log(d.timestamp || ''); } catch(e) {}" <<< "$OUTPUT")
            RESPONSE=$(node -e "try { const d = JSON.parse(require('fs').readFileSync(0, 'utf8')); console.log(d.response || 'No response'); } catch(e) { console.log('Parse error'); }" <<< "$OUTPUT")
          fi
        fi

        [ -z "$TIMESTAMP" ] && TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "response=$RESPONSE" >> $GITHUB_OUTPUT
