name: 'Send Feishu Notification'
description: 'Send notifications to Feishu (飞书) via webhook'
branding:
  icon: 'send'
  color: 'blue'

inputs:
  message:
    description: 'Notification message content'
    required: true
  msg_type:
    description: 'Message type (text, post, or interactive)'
    required: false
    default: 'text'
  title:
    description: 'Message title for post/interactive messages'
    required: false

outputs:
  status:
    description: 'Notification delivery status'
    value: ${{ steps.run.outputs.status }}
  timestamp:
    description: 'ISO 8601 timestamp'
    value: ${{ steps.run.outputs.timestamp }}
  response:
    description: 'Webhook response or error message'
    value: ${{ steps.run.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: cd ${{ github.action_path }} && npm ci --production

    - name: Run notification
      id: run
      shell: bash
      env:
        FEISHU_WEBHOOK_URL: ${{ env.FEISHU_WEBHOOK_URL }}
        FEISHU_MESSAGE: ${{ inputs.message }}
        FEISHU_MSG_TYPE: ${{ inputs.msg_type }}
        FEISHU_TITLE: ${{ inputs.title }}
        HAGI_ACTION_MODE: "true"
      run: |
        cd ${{ github.action_path }}
        OUTPUT=$(npx tsx src/feishu.ts)
        STATUS=$(echo "$OUTPUT" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
        TIMESTAMP=$(echo "$OUTPUT" | grep -o '"timestamp":"[^"]*"' | cut -d'"' -f4)
        RESPONSE=$(echo "$OUTPUT" | grep -o '"response":"[^"]*"' | cut -d'"' -f4 | sed 's/\\"/"/g')
        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "response=$RESPONSE" >> $GITHUB_OUTPUT
